#include <allegro5/color.h>

typedef struct Colors{
    ALLEGRO_COLOR WHITE;
    ALLEGRO_COLOR BLACK;
    ALLEGRO_COLOR CYAN;
    ALLEGRO_COLOR GREEN;
    ALLEGRO_COLOR RED;
    ALLEGRO_COLOR YELLOW;
    ALLEGRO_COLOR ORANGE;
    ALLEGRO_COLOR MEDIUM_VIOLET_RED;
} Colors;

Colors getColors();